      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,STRAN,DSTRAN,
     2 TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,MATERL,NDI,NSHR,NTENS,
     3 NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,
     4 DFGRD0,DFGRD1,NOEL,NPT,KSLAY,KSPT,KSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 MATERL
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),
     4 DFGRD0(3,3),DFGRD1(3,3)
C
	DIMENSION PSTRAIN(3),PS(3),S(6),EMATRIX(NTENS,NTENS)
	REAL PPS,PPSD
	PARAMETER (ONE=1.0D0,TWO=2.0D0,THREE=3.0D0,SIX=6.0D0)
C
C ELASTIC PROPERTIES INPUT
C
       ENU=0.3
       ALPHA = 9.41505e-6
       EMOD=1/ALPHA 
       
       CALL SPRINC(STRESS,PS,1,3,3)
       PPS=MAX(ABS(PS(1)), ABS(PS(2)),ABS(PS(3)))
       PPSD=PPS-PS(1)
           IF (PPSD.LE.1E-5) THEN
              ALPHA = 9.41505e-6
              BELTA = 0.004551
           ELSE
              ALPHA = 9.41505e-6
              BELTA = -0.00348
              PPS=-PPS
	     END IF
	     EMOD=1/ALPHA*(1-BELTA*PPS)**2

	 
	EBULK3=EMOD/(ONE-TWO*ENU)
      EG2=EMOD/(ONE+ENU)
      EG=EG2/TWO
      EG3=THREE*EG
      ELAM=(EBULK3-EG2)/THREE
C
C STIFFNESS MATRIX
C 	
	DO K1=1,NDI
	   DO K2=1,NDI
	     EMATRIX(K2,K1)=ELAM
	   END DO
	  EMATRIX(K1,K1)=TWO*EG+ELAM
	END DO
	DO K3=NDI+1,NTENS
        EMATRIX(K3,K3)=TWO*EG
	END DO
C
C STRESS UPDATE
C 		
	STRESS=STRESS+MATMUL(EMATRIX,DSTRAN)  
C
C DDSDDE
C 		
	DDSDDE=EMATRIX
	STATEV(1)=PS(1)
	STATEV(2)=PS(2)
	STATEV(3)=PS(3)
	STATEV(4)=PPS
	
	RETURN
	END

    